name: Terraform CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # -------------------------------------------------------------------
    # 1. CHECKOUT CODE
    # -------------------------------------------------------------------
    - name: Checkout code
      uses: actions/checkout@v3

    # -------------------------------------------------------------------
    # 2. CONFIGURE AWS WITH OIDC
    # -------------------------------------------------------------------
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::730335466710:role/Sagar-ETL-Role-for-Github
        aws-region: us-east-1

    # -------------------------------------------------------------------
    # 3. SETUP TERRAFORM
    # -------------------------------------------------------------------
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # -------------------------------------------------------------------
    # 4. INIT CONFIGURATION (uses S3 remote backend)
    # -------------------------------------------------------------------
    - name: Terraform Init
      run: terraform init -input=false

    # -------------------------------------------------------------------
    # 5. SELECT WORKSPACE BASED ON BRANCH
    # -------------------------------------------------------------------
    - name: Select Workspace
      run: |
        BRANCH_NAME="${GITHUB_REF##*/}"

        if [[ "$BRANCH_NAME" == "main" ]]; then
          terraform workspace select prod || terraform workspace new prod
        else
          terraform workspace select dev || terraform workspace new dev
        fi

    # -------------------------------------------------------------------
    # 6. TERRAFORM FMT LINT
    # -------------------------------------------------------------------
    - name: Terraform Format Check
      run: terraform fmt -check

    # -------------------------------------------------------------------
    # 7. VALIDATE TERRAFORM SYNTAX
    # -------------------------------------------------------------------
    - name: Terraform Validate
      run: terraform validate

    # -------------------------------------------------------------------
    # 8. PLAN ALWAYS
    # -------------------------------------------------------------------
    - name: Terraform Plan
      run: |
        BRANCH_NAME="${GITHUB_REF##*/}"
        terraform plan -var="env=$BRANCH_NAME"

    # -------------------------------------------------------------------
    # 9. APPLY ONLY ON MAIN (PRODUCTION)
    # -------------------------------------------------------------------
    - name: Terraform Apply (main only)
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve -var="env=prod"
